services:
  - type: web
    name: nova-hub
    env: node
    rootDir: .
    buildCommand: git config --global --add safe.directory '*' && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
