services:
  - type: web
    name: nova-hub
    env: node
    rootDir: HTML5-games-1
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
